# -*- coding: utf-8 -*-
"""SnML.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EuyyH8tQEUtJyc1dGyQ4TiWamkpgiE2m
"""

import numpy as np
import matplotlib.pyplot as plt
from scipy.stats import ttest_ind, f_oneway, pearsonr

"""# Part A - Independent t-Test"""

np.random.seed(42)
group_A = np.random.normal(70, 8, 30)
group_B = np.random.normal(75, 8, 30)

plt.hist(group_A, bins=15, alpha=0.6, label="Group A")
plt.hist(group_B, bins=15, alpha=0.6, label="Group B")
plt.legend()
plt.show()

t_stat, p_value = ttest_ind(group_A, group_B)
print("Mean A:", group_A.mean())
print("Mean B:", group_B.mean())
print("t-statistic:", t_stat)
print("p-value:", p_value)

"""The negative t-statistic indicates that Group A’s mean is lower than Group B’s mean.

The p-value (0.0049) is less than 0.05, which is the common significance level.


Conclusion

Since p < 0.05, we reject the null hypothesis.
There is a statistically significant difference between the average exam scores of Group A and Group B.
This suggests that Group B performed significantly better than Group A.

# Part B: ANOVA
"""

traditional = np.random.normal(70, 7, 30)
online = np.random.normal(74, 7, 30)
blended = np.random.normal(78, 7, 30)

f_stat, p_val = f_oneway(traditional, online, blended)
print("F-statistic:", f_stat)
print("p-value:", p_val)

"""The F-statistic measures the ratio of variance between groups to variance within groups.

The p-value is much smaller than 0.05.

Conclusion

Since p < 0.05, we reject the null hypothesis.
This means that at least one teaching method leads to a significantly different average exam score.
However, ANOVA does not tell which specific group differs, a post-hoc test (e.g Tukey) would be needed for that.

# Part C: Correlation
"""

import numpy as np
from scipy.stats import pearsonr

np.random.seed(42)

# Changed ranges and relationship
study_hours = np.random.uniform(1, 8, 40)
exam_scores = 55 + 3*study_hours + np.random.normal(0, 10, 40)

corr, p_corr = pearsonr(study_hours, exam_scores)

print("Correlation:", corr)
print("p-value:", p_corr)

"""The correlation coefficient is positive, indicating that as study hours increase, exam scores tend to increase.
The value shows a moderate to strong relationship, not perfect.
The p-value < 0.05 indicates the relationship is statistically significant.

Conclusion : There is a statistically significant positive correlation between study hours and exam scores, suggesting that increased study time is generally associated with better performance, though other factors also influence exam results.

"""

