# -*- coding: utf-8 -*-
"""100005915_ Week: 1 (Pre-course / Diagnostic).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lLZ4GPYiWUiCmaPclwRbJE3ECtPZq-ij

DATASET
"""

data = [12, 15, 14, 10, 18, 20, 17, 16, 14, 13]

"""TASK 1 – BASIC PYTHON (NO LIBRARIES)"""

#print
print("Dataset:", data)

#min
min_value = data[0]
for x in data:
    if x < min_value:
        min_value = x

#max
max_value = data[0]
for x in data:
    if x > max_value:
        max_value = x

# Mean
total = 0
for x in data:
    total += x
mean_value = total / len(data)

print("Minimum:", min_value)
print("Maximum:", max_value)
print("Mean:", mean_value)

#sorting
sorted_data = sorted(data)
print("Sorted Data:", sorted_data)

#mediann
n = len(sorted_data)
if n % 2 == 0:
    median_value = (sorted_data[n//2 - 1] + sorted_data[n//2]) / 2
else:
    median_value = sorted_data[n//2]

print("Median:", median_value)

#high frequency
frequency = {}
for x in data:
    frequency[x] = frequency.get(x, 0) + 1

max_freq = max(frequency.values())
most_frequent = [key for key, value in frequency.items() if value == max_freq]

print("Most frequent value(s):", most_frequent)

"""TASK 2 – USING PYTHON PACKAGES



"""

import statistics

mean_lib = statistics.mean(data)
median_lib = statistics.median(data)
std_dev_lib = statistics.stdev(data)

print("Mean:", mean_lib)
print("Median:", median_lib)
print("Standard Deviation:", std_dev_lib)

"""TASK 3 – SIMPLE VISUALIZATION"""

import matplotlib.pyplot as plt

plt.hist(data, bins=5)
plt.title("Histogram of the Dataset")
plt.xlabel("Values")
plt.ylabel("Frequency")
plt.show()

"""TASK 4 – SHORT INTERPRETATION


This dataset appears to represent a small collection of numerical measurements such as test scores or observations.

The spread is moderate, with values ranging from 10 to 20, indicating no extreme outliers.

The value 14 seems most typical, as it occurs most frequently and is close to both the mean and median.

TASK 5 – SMALL FUNCTION
"""

def describe_data(data):
    sorted_data = sorted(data)

    minimum = min(data)
    maximum = max(data)
    mean = sum(data) / len(data)

    n = len(sorted_data)
    if n % 2 == 0:
        median = (sorted_data[n//2 - 1] + sorted_data[n//2]) / 2
    else:
        median = sorted_data[n//2]

    return minimum, maximum, mean, median

# Call the function
result = describe_data(data)
print("Description (min, max, mean, median):", result)