# -*- coding: utf-8 -*-
"""100005915_Exercise Week 1 – Individual.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZBweQV4cKRtwEnnNlAMbboktewL6-y_o
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.datasets import load_iris
from scipy import stats

#Load iris dataset
iris = load_iris()

df = pd.DataFrame(
    iris.data,
    columns=["sepal_length", "sepal_width", "petal_length", "petal_width"]
)

df["species"] = pd.Categorical.from_codes(iris.target, iris.target_names)

df.head()

"""# 1. Descriptive Statistics"""

desc_stats = df.groupby("species")["sepal_length"].agg(
    mean="mean",
    median="median",
    std="std"
)

desc_stats

highest_variability = desc_stats["std"].idxmax()
highest_variability

"""Interpretation : Virginica shows the highest variability in sepal length, indicating greater spread in measurements compared to other species.

# 2. Central Tendency & Dispersion
"""

petal_stats = df.groupby("species")["petal_length"].agg(
    mean="mean",
    median="median",
    variance="var",
    std="std"
)

petal_stats

modes = df.groupby("species")["petal_length"].apply(
    lambda x: stats.mode(x, keepdims=True).mode[0]
)

modes

"""Explanation : The median differs from the mean when the data is skewed or contains outliers, as the mean is more sensitive to extreme values.

# 3. Visualization
"""

#Histogram
plt.hist(df["petal_width"], bins=15)
plt.xlabel("Petal Width")
plt.ylabel("Frequency")
plt.title("Histogram of Petal Width (All Species)")
plt.show()

#Boxplot
df.boxplot(column="sepal_length", by="species")
plt.title("Sepal Length by Species")
plt.suptitle("")
plt.xlabel("Species")
plt.ylabel("Sepal Length")
plt.show()

"""The boxplot better shows between-species differences because it clearly compares medians, spread, and outliers across species.

# 4. Distributions & Skewness
"""

skewness = df.groupby("species")["petal_length"].apply(stats.skew)
skewness

most_positive = skewness.idxmax()
most_negative = skewness.idxmin()

most_positive, most_negative

"""Interpretation : Positive skew indicates a longer right tail, while negative skew indicates a longer left tail. Species differ in petal length symmetry.

# 5. Sampling & Central Limit Theorem
"""

np.random.seed(42)

population = df["sepal_length"]
sample_means = []

for _ in range(100):
    sample = np.random.choice(population, size=20, replace=True)
    sample_means.append(sample.mean())

#Histogram – Sample Means
plt.hist(sample_means, bins=15)
plt.xlabel("Sample Mean")
plt.ylabel("Frequency")
plt.title("Sampling Distribution of the Mean (n=20)")
plt.show()

#Histogram – Original Data
plt.hist(population, bins=15)
plt.xlabel("Sepal Length")
plt.ylabel("Frequency")
plt.title("Original Sepal Length Distribution")
plt.show()

"""Comparison : The sampling distribution is more normal and concentrated around the mean, demonstrating the Central Limit Theorem.

# 6. Correlation
"""

r, p = stats.pearsonr(df["sepal_length"], df["petal_length"])
r, p

#Scatter Plot with Best-Fit Line
plt.scatter(df["sepal_length"], df["petal_length"])
m, b = np.polyfit(df["sepal_length"], df["petal_length"], 1)
plt.plot(df["sepal_length"], m*df["sepal_length"] + b)
plt.xlabel("Sepal Length")
plt.ylabel("Petal Length")
plt.title("Sepal Length vs Petal Length")
plt.show()

"""Result : The relationship is positive, meaning petal length increases as sepal length increases.

# 7. Hypothesis Testing: t-Test (2 Groups)
"""

setosa = df[df["species"] == "setosa"]["petal_length"]
versicolor = df[df["species"] == "versicolor"]["petal_length"]

t_stat, p_val = stats.ttest_ind(setosa, versicolor)
t_stat, p_val

"""Conclusion : Since the p-value is less than 0.05, we reject the null hypothesis and conclude that the mean petal lengths differ significantly.

# 8. Hypothesis Testing: ANOVA (3 Groups)
"""

virginica = df[df["species"] == "virginica"]["petal_width"]

f_stat, p_val = stats.f_oneway(setosa, versicolor, virginica)
f_stat, p_val

"""Conclusion : The ANOVA test shows a statistically significant difference in petal width across species."""